import styles from './ListaCompras.module.css'

export default function ListaCompras () {
    return (
        <>
            <p>Commodo esse aliquip nisi ullamco id ut consectetur eu laborum laborum sit labore reprehenderit dolore. Et id velit nulla laborum ullamco sit ea Lorem. Esse sint fugiat duis deserunt aute eu dolor minim aliqua deserunt ea enim enim. Consectetur deserunt minim elit amet fugiat nulla incididunt eiusmod ut ipsum. Do minim exercitation aliquip dolor est eu cillum enim minim excepteur adipisicing velit. Dolor elit voluptate ea elit aliquip incididunt veniam qui ad sunt. Est est cupidatat quis sint duis consequat irure sint enim culpa sit non aliqua.</p>
            <p>Commodo esse aliquip nisi ullamco id ut consectetur eu laborum laborum sit labore reprehenderit dolore. Et id velit nulla laborum ullamco sit ea Lorem. Esse sint fugiat duis deserunt aute eu dolor minim aliqua deserunt ea enim enim. Consectetur deserunt minim elit amet fugiat nulla incididunt eiusmod ut ipsum. Do minim exercitation aliquip dolor est eu cillum enim minim excepteur adipisicing velit. Dolor elit voluptate ea elit aliquip incididunt veniam qui ad sunt. Est est cupidatat quis sint duis consequat irure sint enim culpa sit non aliqua.</p>
            <p>Commodo esse aliquip nisi ullamco id ut consectetur eu laborum laborum sit labore reprehenderit dolore. Et id velit nulla laborum ullamco sit ea Lorem. Esse sint fugiat duis deserunt aute eu dolor minim aliqua deserunt ea enim enim. Consectetur deserunt minim elit amet fugiat nulla incididunt eiusmod ut ipsum. Do minim exercitation aliquip dolor est eu cillum enim minim excepteur adipisicing velit. Dolor elit voluptate ea elit aliquip incididunt veniam qui ad sunt. Est est cupidatat quis sint duis consequat irure sint enim culpa sit non aliqua.</p>
            <p>Commodo esse aliquip nisi ullamco id ut consectetur eu laborum laborum sit labore reprehenderit dolore. Et id velit nulla laborum ullamco sit ea Lorem. Esse sint fugiat duis deserunt aute eu dolor minim aliqua deserunt ea enim enim. Consectetur deserunt minim elit amet fugiat nulla incididunt eiusmod ut ipsum. Do minim exercitation aliquip dolor est eu cillum enim minim excepteur adipisicing velit. Dolor elit voluptate ea elit aliquip incididunt veniam qui ad sunt. Est est cupidatat quis sint duis consequat irure sint enim culpa sit non aliqua.</p>
            <p>Commodo esse aliquip nisi ullamco id ut consectetur eu laborum laborum sit labore reprehenderit dolore. Et id velit nulla laborum ullamco sit ea Lorem. Esse sint fugiat duis deserunt aute eu dolor minim aliqua deserunt ea enim enim. Consectetur deserunt minim elit amet fugiat nulla incididunt eiusmod ut ipsum. Do minim exercitation aliquip dolor est eu cillum enim minim excepteur adipisicing velit. Dolor elit voluptate ea elit aliquip incididunt veniam qui ad sunt. Est est cupidatat quis sint duis consequat irure sint enim culpa sit non aliqua.</p>
            <p>Commodo esse aliquip nisi ullamco id ut consectetur eu laborum laborum sit labore reprehenderit dolore. Et id velit nulla laborum ullamco sit ea Lorem. Esse sint fugiat duis deserunt aute eu dolor minim aliqua deserunt ea enim enim. Consectetur deserunt minim elit amet fugiat nulla incididunt eiusmod ut ipsum. Do minim exercitation aliquip dolor est eu cillum enim minim excepteur adipisicing velit. Dolor elit voluptate ea elit aliquip incididunt veniam qui ad sunt. Est est cupidatat quis sint duis consequat irure sint enim culpa sit non aliqua.</p>
            <p>Commodo esse aliquip nisi ullamco id ut consectetur eu laborum laborum sit labore reprehenderit dolore. Et id velit nulla laborum ullamco sit ea Lorem. Esse sint fugiat duis deserunt aute eu dolor minim aliqua deserunt ea enim enim. Consectetur deserunt minim elit amet fugiat nulla incididunt eiusmod ut ipsum. Do minim exercitation aliquip dolor est eu cillum enim minim excepteur adipisicing velit. Dolor elit voluptate ea elit aliquip incididunt veniam qui ad sunt. Est est cupidatat quis sint duis consequat irure sint enim culpa sit non aliqua.</p>
        </>
    )
}